services:
    kalinka.authorizer:
        class: AC\KalinkaBundle\ContainerAwareRoleAuthorizer
        arguments:
            - @security.context
            - @service_container
            - %kalinka.authorizer.default.role_map%
            - %kalinka.authorizer.default.anonymous_role%
            - %kalinka.authorizer.default.authenticated_role%
        tags:
            - { name: kalinka.authorizer, tag: default }

    kalinka.hypothetical_request_subscriber:
        class: AC\KalinkaBundle\EventDispatcher\HypotheticalRequestSubscriber
        arguments:
            - @kalinka.authorizer
        tags:
            - { name: kernel.event_subscriber }

    jms_serializer.subscriber.document:
        class: AC\KalinkaBundle\EventDispatcher\KalinkaAuthorizationSubscriber
        arguments: [@kalinka.authorizer, @annotation_reader]
        tags:
            - { name: jms_serializer.event_subscriber }
